# Generated by Django 3.1 on 2020-10-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReLearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='ReLearn',
        ),
    ]
